// Code generated by MockGen. DO NOT EDIT.
// Source: internal/backup/file_audit.go
//
// Generated by this command:
//
//	mockgen -source=internal/backup/file_audit.go -destination=internal/backup/mocks/mock_file_audit.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	audit "github.com/IsaacDSC/auditory/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditStore is a mock of AuditStore interface.
type MockAuditStore struct {
	ctrl     *gomock.Controller
	recorder *MockAuditStoreMockRecorder
	isgomock struct{}
}

// MockAuditStoreMockRecorder is the mock recorder for MockAuditStore.
type MockAuditStoreMockRecorder struct {
	mock *MockAuditStore
}

// NewMockAuditStore creates a new mock instance.
func NewMockAuditStore(ctrl *gomock.Controller) *MockAuditStore {
	mock := &MockAuditStore{ctrl: ctrl}
	mock.recorder = &MockAuditStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditStore) EXPECT() *MockAuditStoreMockRecorder {
	return m.recorder
}

// Upsert mocks base method.
func (m *MockAuditStore) Upsert(ctx context.Context, input audit.DataAudit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockAuditStoreMockRecorder) Upsert(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockAuditStore)(nil).Upsert), ctx, input)
}

// MockIdempotencyStore is a mock of IdempotencyStore interface.
type MockIdempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyStoreMockRecorder
	isgomock struct{}
}

// MockIdempotencyStoreMockRecorder is the mock recorder for MockIdempotencyStore.
type MockIdempotencyStoreMockRecorder struct {
	mock *MockIdempotencyStore
}

// NewMockIdempotencyStore creates a new mock instance.
func NewMockIdempotencyStore(ctrl *gomock.Controller) *MockIdempotencyStore {
	mock := &MockIdempotencyStore{ctrl: ctrl}
	mock.recorder = &MockIdempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyStore) EXPECT() *MockIdempotencyStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIdempotencyStore) Get(key string) (time.Time, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdempotencyStoreMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdempotencyStore)(nil).Get), key)
}

// Set mocks base method.
func (m *MockIdempotencyStore) Set(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key)
}

// Set indicates an expected call of Set.
func (mr *MockIdempotencyStoreMockRecorder) Set(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIdempotencyStore)(nil).Set), key)
}
