// Code generated by MockGen. DO NOT EDIT.
// Source: internal/backup/bucket_backup.go
//
// Generated by this command:
//
//	mockgen -source=internal/backup/bucket_backup.go -destination=internal/backup/mocks/mock_bucket_backup.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	store "github.com/IsaacDSC/auditory/internal/store"
	gomock "go.uber.org/mock/gomock"
)

// MockFileStore is a mock of FileStore interface.
type MockFileStore struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreMockRecorder
	isgomock struct{}
}

// MockFileStoreMockRecorder is the mock recorder for MockFileStore.
type MockFileStoreMockRecorder struct {
	mock *MockFileStore
}

// NewMockFileStore creates a new mock instance.
func NewMockFileStore(ctrl *gomock.Controller) *MockFileStore {
	mock := &MockFileStore{ctrl: ctrl}
	mock.recorder = &MockFileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStore) EXPECT() *MockFileStoreMockRecorder {
	return m.recorder
}

// DeleteAfterDay mocks base method.
func (m *MockFileStore) DeleteAfterDay(ctx context.Context, timeNow time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAfterDay", ctx, timeNow)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAfterDay indicates an expected call of DeleteAfterDay.
func (mr *MockFileStoreMockRecorder) DeleteAfterDay(ctx, timeNow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAfterDay", reflect.TypeOf((*MockFileStore)(nil).DeleteAfterDay), ctx, timeNow)
}

// GetAll mocks base method.
func (m *MockFileStore) GetAll(ctx context.Context) (map[string]store.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(map[string]store.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFileStoreMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFileStore)(nil).GetAll), ctx)
}

// MockS3Store is a mock of S3Store interface.
type MockS3Store struct {
	ctrl     *gomock.Controller
	recorder *MockS3StoreMockRecorder
	isgomock struct{}
}

// MockS3StoreMockRecorder is the mock recorder for MockS3Store.
type MockS3StoreMockRecorder struct {
	mock *MockS3Store
}

// NewMockS3Store creates a new mock instance.
func NewMockS3Store(ctrl *gomock.Controller) *MockS3Store {
	mock := &MockS3Store{ctrl: ctrl}
	mock.recorder = &MockS3StoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Store) EXPECT() *MockS3StoreMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockS3Store) Backup(ctx context.Context, timeNow time.Time, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx, timeNow, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Backup indicates an expected call of Backup.
func (mr *MockS3StoreMockRecorder) Backup(ctx, timeNow, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockS3Store)(nil).Backup), ctx, timeNow, data)
}

// Save mocks base method.
func (m *MockS3Store) Save(ctx context.Context, dataKey string, timeNow time.Time, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, dataKey, timeNow, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockS3StoreMockRecorder) Save(ctx, dataKey, timeNow, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockS3Store)(nil).Save), ctx, dataKey, timeNow, data)
}
