// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/control-plane/internal/handle/manual_store.go
//
// Generated by this command:
//
//	mockgen -source=cmd/control-plane/internal/handle/manual_store.go -destination=cmd/control-plane/internal/handle/mocks/mock_manual_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManualStoreService is a mock of ManualStoreService interface.
type MockManualStoreService struct {
	ctrl     *gomock.Controller
	recorder *MockManualStoreServiceMockRecorder
	isgomock struct{}
}

// MockManualStoreServiceMockRecorder is the mock recorder for MockManualStoreService.
type MockManualStoreServiceMockRecorder struct {
	mock *MockManualStoreService
}

// NewMockManualStoreService creates a new mock instance.
func NewMockManualStoreService(ctrl *gomock.Controller) *MockManualStoreService {
	mock := &MockManualStoreService{ctrl: ctrl}
	mock.recorder = &MockManualStoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManualStoreService) EXPECT() *MockManualStoreServiceMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockManualStoreService) Store(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockManualStoreServiceMockRecorder) Store(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockManualStoreService)(nil).Store), ctx)
}
