// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/control-plane/internal/handle/manual_backup.go
//
// Generated by this command:
//
//	mockgen -source=cmd/control-plane/internal/handle/manual_backup.go -destination=cmd/control-plane/internal/handle/mocks/mock_manual_backup.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManualBackupService is a mock of ManualBackupService interface.
type MockManualBackupService struct {
	ctrl     *gomock.Controller
	recorder *MockManualBackupServiceMockRecorder
	isgomock struct{}
}

// MockManualBackupServiceMockRecorder is the mock recorder for MockManualBackupService.
type MockManualBackupServiceMockRecorder struct {
	mock *MockManualBackupService
}

// NewMockManualBackupService creates a new mock instance.
func NewMockManualBackupService(ctrl *gomock.Controller) *MockManualBackupService {
	mock := &MockManualBackupService{ctrl: ctrl}
	mock.recorder = &MockManualBackupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManualBackupService) EXPECT() *MockManualBackupServiceMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockManualBackupService) Backup(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Backup indicates an expected call of Backup.
func (mr *MockManualBackupServiceMockRecorder) Backup(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockManualBackupService)(nil).Backup), ctx)
}
