// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/control-plane/internal/handle/audit_store.go
//
// Generated by this command:
//
//	mockgen -source=cmd/control-plane/internal/handle/audit_store.go -destination=cmd/control-plane/internal/handle/mocks/mock_audit_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/IsaacDSC/auditory/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditStoreService is a mock of AuditStoreService interface.
type MockAuditStoreService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditStoreServiceMockRecorder
	isgomock struct{}
}

// MockAuditStoreServiceMockRecorder is the mock recorder for MockAuditStoreService.
type MockAuditStoreServiceMockRecorder struct {
	mock *MockAuditStoreService
}

// NewMockAuditStoreService creates a new mock instance.
func NewMockAuditStoreService(ctrl *gomock.Controller) *MockAuditStoreService {
	mock := &MockAuditStoreService{ctrl: ctrl}
	mock.recorder = &MockAuditStoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditStoreService) EXPECT() *MockAuditStoreServiceMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockAuditStoreService) Save(ctx context.Context, input audit.DataAudit) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockAuditStoreServiceMockRecorder) Save(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditStoreService)(nil).Save), ctx, input)
}
